export let cryptoCurrencies = [
  '020LondonCoin',
  '0x',
  '1337',
  '2GIVE',
  '300 Token',
  '42-coin',
  '808Coin',
  '8Bit',
  '9COIN',
  'ALIS',
  'AMIS',
  'APX',
  'ARbit',
  'ATBCoin',
  'ATC Coin',
  'ATMChain',
  'ATMCoin',
  'Abncoin',
  'Aces',
  'Achain',
  'Acoin',
  'AdCoin',
  'AdEx',
  'AdShares',
  'Adelphoi',
  'Advanced Internet Blocks',
  'Adzcoin',
  'Aeon',
  'Aeternity',
  'Agoras Tokens',
  'Agrello',
  'AgrolifeCoin',
  'Aidos Kuneen',
  'Aion',
  'AirSwap',
  'AirToken',
  'Akuya Coin',
  'AllSafe',
  'Allion',
  'AlpaCoin',
  'Alphabit',
  'Altcoin',
  'AmberCoin',
  'Ammo Rewards',
  'AmsterdamCoin',
  'AnarchistsPrime',
  'Animecoin',
  'Anoncoin',
  'AntiBitcoin',
  'Antilitecoin',
  'Antimatter',
  'AppleCoin',
  'AquariusCoin',
  'Aragon',
  'Arcade Token',
  'ArcticCoin',
  'Ardor',
  'Argentum',
  'Argus',
  'Aricoin',
  'Ark',
  'ArtByte',
  'Artex Coin',
  'Asch',
  'Aseancoin',
  'AsiaCoin',
  'Asiadigicoin',
  'AsicCoin',
  'Atmos',
  'Atomic Coin',
  'AudioCoin',
  'Augur',
  'Aureus',
  'Auroracoin',
  'AurumCoin',
  'Authorship',
  'AvatarCoin',
  'Aventus',
  'Avoncoin',
  'AxFunds',
  'Axiom',
  'B3Coin',
  'BBQCoin',
  'BCAP',
  'BERNcash',
  'BITFID',
  'BRAT',
  'BTCGold',
  'BTCtalkcoin',
  'BTSR',
  'Bancor',
  'Bankcoin',
  'Basic Attention Token',
  'Bastonet',
  'BatCoin',
  'Bata',
  'Beatcoin',
  'BeaverCoin',
  'Bela',
  'BenjiRolls',
  'BestChain',
  'BetaCoin',
  'BiblePay',
  'BigUp',
  'BillaryCoin',
  'Billionaire Token',
  'Binance Coin',
  'BioBar',
  'BiosCrypto',
  'BipCoin',
  'Birds',
  'Bismuth',
  'Bit20',
  'BitAlphaCoin',
  'BitAsean',
  'BitBar',
  'BitBay',
  'BitBean',
  'BitCentavo',
  'BitCoal',
  'BitConnect',
  'BitDice',
  'BitQuark',
  'BitSend',
  'BitShares',
  'BitSoar',
  'BitTokens',
  'Bitcedi',
  'Bitcloud',
  'Bitcoin',
  'Bitcoin 21',
  'Bitcoin Cash',
  'Bitcoin Planet',
  'Bitcoin Plus',
  'Bitcoin Scrypt',
  'Bitcoin Unlimited (Futures)',
  'BitcoinCashScrypt',
  'BitcoinDark',
  'BitcoinFast',
  'BitcoinZ',
  'Bitcore',
  'Bitcrystals',
  'Bitcurrency',
  'Bitdeal',
  'Bitgem',
  'Bitland',
  'Bitmark',
  'Bitok',
  'Bitpark Coin',
  'Bitquence',
  'Bitradio',
  'Bitstar',
  'Bitswift',
  'Bitvolt',
  'Bitz',
  'Bitzeny',
  'BlackCoin',
  'Blackmoon Crypto',
  'Blackstar',
  'BlakeStar',
  'Blakecoin',
  'BlazeCoin',
  'BlazerCoin',
  'Blitzcash',
  'BlockCAT',
  'BlockMason Credit Protocol',
  'BlockPay',
  'Blockchain Index',
  'Blocknet',
  'Blocktix',
  'BlueCoin',
  'BnrtxCoin',
  'Bolenum',
  'Bolivarcoin',
  'Bongger',
  'BoostCoin',
  'Bottlecaps',
  'Bowhead',
  'BowsCoin',
  'Braincoin',
  'Breakout',
  'Breakout Stake',
  'BriaCoin',
  'BridgeCoin',
  'BritCoin',
  'Bubble',
  'BumbaCoin',
  'BunnyCoin',
  'Burst',
  'BurstOcean',
  'BuzzCoin',
  'Byteball Bytes',
  'Bytecent',
  'Bytecoin',
  'Bytom',
  'C-Bit',
  'CBD Crystals',
  'CCMiner',
  'CHIPS',
  'CHNCoin',
  'CORION',
  'COSS',
  'CRTCoin',
  'CVCoin',
  'Cabbage',
  'CacheCoin',
  'CageCoin',
  'Californium',
  'CaliphCoin',
  'CampusCoin',
  'Canada eCoin',
  'CannabisCoin',
  'Cannacoin',
  'Cannation',
  'Capricoin',
  'Carboncoin',
  'Cardano',
  'Cashcoin',
  'Cashme',
  'Casino',
  'CasinoCoin',
  'Catcoin',
  'Centra',
  'Centurion',
  'ChainCoin',
  'ChainLink',
  'ChanCoin',
  'Change',
  'Cheapcoin',
  'ChessCoin',
  'Chronobank',
  'Chronologic',
  'Chronos',
  'Cindicator',
  'Circuits of Value',
  'Civic',
  'Clams',
  'Clinton',
  'CloakCoin',
  'ClubCoin',
  'CoExistCoin',
  'Cobinhood',
  'Cofound.it',
  'Coimatic 2.0',
  'Coimatic 3.0',
  'Coin(O)',
  'Coin2.1',
  'CoinDash',
  'Coinonat',
  'CoinonatX',
  'ColossusCoinXT',
  'Colossuscoin V2',
  'Comet',
  'Compcoin',
  'CompuCoin',
  'Concoin',
  'Condensate',
  'CorgiCoin',
  'Counterparty',
  'Coupecoin',
  'Crave',
  'Cream',
  'Creatio',
  'Creativecoin',
  'Creditbit',
  'Credo',
  'CrevaCoin',
  'Crown',
  'CryptCoin',
  'Crypto',
  'Crypto Bullion',
  'CryptoCarbon',
  'CryptoEscudo',
  'CryptoForecast',
  'CryptoPing',
  'CryptoWorldX Token',
  'Cryptojacks',
  'Cryptonex',
  'Cryptonite',
  'Crystal Clear ',
  'Cthulhu Offerings',
  'Cubits',
  'Curecoin',
  'CybCSec',
  'CyberCoin',
  'Cycling Coin',
  'Cyder',
  'Cypher',
  'DAO.Casino',
  'DAPPSTER',
  'DAS',
  'DECENT',
  'DFSCoin',
  'DIBCOIN',
  'DNotes',
  'DPAY',
  'DROXNE',
  'DT Token',
  'Dalecoin',
  'Darcrus',
  'DarkLisk',
  'Darsek',
  'Dash',
  'Dashcoin',
  'Dashs',
  'Databits',
  'DaxxCoin',
  'Debitcoin',
  'Decentraland',
  'Decred',
  'DeepOnion',
  'DeltaCredits',
  'Denarius',
  'Dent',
  'Dentacoin',
  'Destiny',
  'DeusCoin',
  'Deutsche eMark',
  'Devcoin',
  'Diamond',
  'DigiByte',
  'DigiCube',
  'Digital Bullion Gold',
  'Digital Credits',
  'Digital Money Bits',
  'Digital Rupees',
  'DigitalDevelopersFund',
  'DigitalNote',
  'DigitalPrice',
  'Digitalcoin',
  'DigixDAO',
  'Dimecoin',
  'Dinastycoin',
  'Dix Asset',
  'Dogecoin',
  'Dollar Online',
  'Dollarcoin',
  'DomRaider',
  'Donationcoin',
  'DopeCoin',
  'Dotcoin',
  'Doubloon',
  'DraftCoin',
  'Dreamcoin',
  'DubaiCoin',
  'Dubstep',
  'Dutch Coin',
  'Dynamic',
  'DynamicCoin',
  'E-Currency Coin',
  'E-Dinar Coin',
  'E-coin',
  'E4ROW',
  'EDRCoin',
  'EGO',
  'EMoneyPower',
  'EOS',
  'EOT Token',
  'EarthCoin',
  'Ebittree Coin',
  'EcoCoin',
  'Ecobit',
  'Edgeless',
  'EggCoin',
  'Eidoo',
  'Einsteinium',
  'Elacoin',
  'Elastic',
  'Elcoin',
  'Electra',
  'Elementrem',
  'Elixir',
  'Elysium',
  'EmberCoin',
  'Embers',
  'Emerald Crypto',
  'Emercoin',
  'EncryptoTel [ETH]',
  'EncryptoTel [WAVES]',
  'Energycoin',
  'Enigma',
  'Enigma',
  'Environ',
  'EquiTrader',
  'Ergo',
  'Eryllium',
  'Espers',
  'Eternity',
  'EthBet',
  'Ethbits',
  'EtherDoge',
  'Ethereum',
  'Ethereum Blue',
  'Ethereum Cash',
  'Ethereum Classic',
  'Ethereum Dark',
  'Ethereum Gold',
  'Ethereum Movie Venture',
  'Etheriya',
  'Etheroll',
  'Etherx',
  'Eurocoin',
  'EuropeCoin',
  'EverGreenCoin',
  'Everex',
  'Everus',
  'Evil Coin',
  'Evotion',
  'Excelcoin',
  'ExchangeN',
  'ExclusiveCoin',
  'Expanse',
  'FIMKrypto',
  'FLiK',
  'FUNCoin',
  'Facecoin',
  'Factom',
  'FairCoin',
  'Falcoin',
  'Fantomcoin',
  'Fargocoin',
  'Fastcoin',
  'Fazzcoin',
  'Feathercoin',
  'FedoraCoin',
  'FinCoin',
  'FireFlyCoin',
  'Firecoin',
  'First Bitcoin',
  'First Bitcoin Capital',
  'FirstBlood',
  'FirstCoin',
  'FlappyCoin',
  'Flash',
  'FlavorCoin',
  'Flaxscript',
  'FlorinCoin',
  'FlutterCoin',
  'Flycoin',
  'FoldingCoin',
  'Fonziecoin',
  'Footy Cash',
  'Francs',
  'Franko',
  'FrankyWillCoin',
  'Frazcoin',
  'Freicoin',
  'FuckToken',
  'FuelCoin',
  'FujiCoin',
  'Fujinto',
  'FunFair',
  'FundYourselfNow',
  'FutCoin',
  'FuturXe',
  'Future Digital Currency',
  'FuzzBalls',
  'G3N',
  'GAIA',
  'GAY Money',
  'GBCGoldCoin',
  'GCoin',
  'GO! Coin',
  'GPU Coin',
  'GXShares',
  'Gambit',
  'GameBet Coin',
  'GameCredits',
  'GameLeagueCoin',
  'GameUnits',
  'GanjaCoin',
  'Gapcoin',
  'Gas',
  'GeertCoin',
  'GeoCoin',
  'GeyserCoin',
  'Giga Watt Token',
  'Global Business Revolution',
  'Global Currency Reserve',
  'Global Tour Coin',
  'GlobalBoost-Y',
  'GlobalCoin',
  'GlobalToken',
  'Gnosis',
  'Gokucoin',
  'Gold Pressed Latinum',
  'GoldBlocks',
  'GoldCoin',
  'GoldMaxCoin',
  'GoldPieces',
  'GoldReserve',
  'GoldUnionCoin',
  'Golem',
  'Golfcoin',
  'Golos',
  'Golos Gold',
  'Goodomy',
  'Granite',
  'Grantcoin',
  'Greencoin',
  'GridCoin',
  'Groestlcoin',
  'Growers International',
  'GuccioneCoin',
  'Gulden',
  'GulfCoin',
  'Guncoin',
  'HEAT',
  'HODL Bucks',
  'HOdlcoin',
  'HTMLCOIN',
  'Hacker Gold',
  'Halcyon',
  'Halloween Coin',
  'Happy Creator Coin',
  'Happycoin',
  'HarmonyCoin',
  'HealthyWormCoin',
  'Helleniccoin',
  'HelloGold',
  'HempCoin',
  'HempCoin',
  'Hexx',
  'HiCoin',
  'High Voltage',
  'HitCoin',
  'Hive',
  'HoboNickels',
  'Honey',
  'Hshare',
  'Hubii Network',
  'Humaniq',
  'Huncoin',
  'HunterCoin',
  'Hush',
  'Hyper',
  'HyperStake',
  'I/O Coin',
  'I0Coin',
  'ICO OpenLedger',
  'ICOBID',
  'ION',
  'IOTA',
  'Iconic',
  'Iconomi',
  'Impact',
  'ImpulseCoin',
  'InPay',
  'IncaKoin',
  'Incent',
  'Independent Money System',
  'India Coin',
  'Indorse Token',
  'InfChain',
  'Infinitecoin',
  'Infinity Economics',
  'InflationCoin',
  'Influxcoin',
  'InsaneCoin',
  'International Diamond',
  'Internet of People',
  'Internet of Things',
  'Internxt',
  'Interzone',
  'InvestFeed',
  'InvisibleCoin',
  'IrishCoin',
  'IslaCoin',
  'Ixcoin',
  'JIO Token',
  'Janus',
  'Jetcoin',
  'Jewels',
  'Jin Coin',
  'Jinn',
  'JobsCoin',
  'Joincoin',
  'Joulecoin',
  'Karbowanec',
  'Karmacoin',
  'KashhCoin',
  'Kayicoin',
  'KekCoin',
  'KexCoin',
  'KibiCoin',
  'KickCoin',
  'KiloCoin',
  'Kin',
  'KingN Coin',
  'Kittehcoin',
  'Kobocoin',
  'Kolion',
  'Komodo',
  'Kore',
  'Kronecoin',
  'Kurrent',
  'KushCoin',
  'Kyber Network',
  'LAthaan',
  'LBRY Credits',
  'LEOcoin',
  'LLToken',
  'LTBcoin',
  'Lampix',
  'LanaCoin',
  'LandCoin',
  'Lazaruscoin',
  'LePen',
  'LeaCoin',
  'Legends Room',
  'LetItRide',
  'LeviarCoin',
  'LevoPlus',
  'Lex4All',
  'Linda',
  'Link Platform',
  'LinkedCoin',
  'Linx',
  'Lisk',
  'LiteBar',
  'LiteBitcoin',
  'LiteCoin Ultra',
  'LiteDoge',
  'Litecoin',
  'Litecoin Plus',
  'Litecred',
  'LoMoCoin',
  'Loopring',
  'LottoCoin',
  'LuckChain',
  'Luna Coin',
  'Lunyr',
  'Lykke',
  'MACRON',
  'MCAP',
  'MIYUCoin',
  'MMXVI',
  'MSD',
  'MTMGaming',
  'Machinecoin',
  'Macro',
  'Maecenas',
  'Magi',
  'Magnetcoin',
  'Magnum',
  'MaidSafeCoin',
  'MantraCoin',
  'Mao Zedong',
  'Marijuanacoin',
  'Marscoin',
  'MarteXcoin',
  'MarxCoin',
  'Master Swiscoin',
  'Masternodecoin',
  'Matchpool',
  'Mavro',
  'MaxCoin',
  'MazaCoin',
  'Megacoin',
  'Melon',
  'Memetic',
  'Mercury',
  'MergeCoin',
  'Metal',
  'Metal Music Coin',
  'MetalCoin',
  'Metaverse ETP',
  'MikeTheMug',
  'MiloCoin',
  'Mind Gene',
  'MindCoin',
  'Minereum',
  'Miners\' Reward Token',
  'Mineum',
  'Minex',
  'Mintcoin',
  'MobileCash',
  'MobileGo',
  'Moeda Loyalty Points',
  'Moin',
  'MojoCoin',
  'MonaCoin',
  'Monaco',
  'MonacoCoin',
  'Monero',
  'Moneta',
  'MonetaryUnit',
  'Monetha',
  'Money',
  'MoneyCoin',
  'Monster Byte',
  'Mooncoin',
  'MorningStar',
  'Mothership',
  'Motocoin',
  'Musicoin',
  'MustangCoin',
  'MyBit Token',
  'Myriad',
  'Mysterium',
  'NAV Coin',
  'NEM',
  'NEO',
  'NEVERDIE',
  'NVO',
  'Namecoin',
  'NamoCoin',
  'NautilusCoin',
  'Neblio',
  'NeosCoin',
  'Neptune Classic',
  'NetCoin',
  'Netko',
  'Neuro',
  'NeuroDAO',
  'Neutron',
  'NevaCoin',
  'NewYorkCoin',
  'Newbium',
  'Nexium',
  'Nexus',
  'Nimiq',
  'NoLimitCoin',
  'NobleCoin',
  'NodeCoin',
  'Novacoin',
  'NuBits',
  'NuShares',
  'Numeraire',
  'Nxt',
  'Nyancoin',
  'OAX',
  'OBITS',
  'OCOW',
  'OHM',
  'OKCash',
  'OX Fina',
  'Obsidian',
  'Oceanlab',
  'OctoCoin',
  'Omicron',
  'OmiseGO',
  'Omni',
  'Onix',
  'Opal',
  'Operand',
  'Opescoin',
  'Opus',
  'OracleChain',
  'Orbitcoin',
  'Orlycoin',
  'Ormeus Coin',
  'OsmiumCoin',
  'P7Coin',
  'PIECoin',
  'PIVX',
  'PLNcoin',
  'PRCoin',
  'PRIZM',
  'PX',
  'Pabyosi Coin (Special)',
  'Paccoin',
  'Pakcoin',
  'Pandacoin',
  'ParallelCoin',
  'ParkByte',
  'Particl',
  'Pascal Coin',
  'Pascal Lite',
  'Patientory',
  'PayCoin',
  'PayCon',
  'PayPeer',
  'PayPie',
  'Peacecoin',
  'PeepCoin',
  'Peercoin',
  'Peerplays',
  'PeopleCoin',
  'Pepe Cash',
  'Pesetacoin',
  'Pesobit',
  'PetroDollar',
  'Philosopher Stones',
  'Phoenixcoin',
  'Photon',
  'PiCoin',
  'Piggycoin',
  'Pillar',
  'PinkCoin',
  'PinkDog',
  'PiplCoin',
  'Pirate Blocks',
  'PizzaCoin',
  'PlatinumBAR',
  'Pluton',
  'Po.et',
  'PoSToken',
  'PoSW Coin',
  'PokeCoin',
  'Polybius',
  'PonziCoin',
  'PopularCoin',
  'Populous',
  'PosEx',
  'PostCoin',
  'PotCoin',
  'Powercoin',
  'President Johnson',
  'President Trump',
  'Primalbase Token',
  'Primas',
  'Prime-XI',
  'Primecoin',
  'Primulon',
  'Printerium',
  'PrismChain',
  'ProCurrency',
  'Project Decorum',
  'Project-X',
  'Propy',
  'Prospectors Gold',
  'Protean',
  'Prototanium',
  'Psilocybin',
  'Pulse',
  'Pura',
  'PureVidz',
  'PutinCoin',
  'Qibuck Asset',
  'Qora',
  'Qtum',
  'Quantum',
  'Quantum Resistant Ledger',
  'Quark',
  'Quatloo',
  'QuazarCoin',
  'QubitCoin',
  'Quebecoin',
  'Quotient',
  'Qwark',
  'RChain',
  'REAL',
  'REX',
  'RHFCoin',
  'RSGPcoin',
  'RabbitCoin',
  'Radium',
  'RaiBlocks',
  'Ratecoin',
  'Rawcoin',
  'Rcoin',
  'RedCoin',
  'ReddCoin',
  'ReeCoin',
  'Regacoin',
  'Regalcoin',
  'Remicoin',
  'Renos',
  'Request Network',
  'Revenu',
  'RevolverCoin',
  'Rialto',
  'RichCoin',
  'Ride My Car',
  'Riecoin',
  'Rimbit',
  'Ripple',
  'Ripto Bux',
  'Rise',
  'Rivetz',
  'RonPaulCoin',
  'RouletteToken',
  'Royal Kingdom Coin',
  'RoyalCoin',
  'Royalties',
  'Rubies',
  'RubleBit',
  'Rubycoin',
  'Rupaya',
  'Rupee',
  'RussiaCoin',
  'Rustbits',
  'SACoin',
  'SALT',
  'SHACoin',
  'SIBCoin',
  'SIGMAcoin',
  'SOILcoin',
  'SONM',
  'STEX',
  'Safe Exchange Coin',
  'Safe Trade Coin',
  'SafeCoin',
  'Sakuracoin',
  'SaluS',
  'Sand Coin',
  'Santiment Network Token',
  'Sativacoin',
  'SatoshiMadness',
  'Save and Gain',
  'Scorecoin',
  'SecretCoin',
  'SecureCoin',
  'SegWit2x [Futures]',
  'Selfiecoin',
  'Senderon',
  'Sequence',
  'Sexcoin',
  'Shadow Token',
  'ShadowCash',
  'Sharkcoin',
  'ShellCoin',
  'Shift',
  'Shilling',
  'Shorty',
  'Siacoin',
  'Signatum',
  'SingularDTV',
  'SixEleven',
  'Skeincoin',
  'SkinCoin',
  'Skycoin',
  'Slevin',
  'Slimcoin',
  'Sling',
  'Smart Investment Fund Token',
  'SmartCash',
  'SmartCoin',
  'SmileyCoin',
  'Smoke',
  'SnakeEyes',
  'Soarcoin',
  'Social',
  'SocialCoin',
  'Sojourn',
  'SolarCoin',
  'Solarflarecoin',
  'Solaris',
  'SongCoin',
  'SoonCoin',
  'SoulCoin',
  'Sovereign Hero',
  'SpaceCoin',
  'Spectrecoin',
  'Speedcash',
  'Sphere',
  'Sphre AIR ',
  'SportsCoin',
  'Spots',
  'SpreadCoin',
  'Sprouts',
  'SproutsExtreme',
  'Stakecoin',
  'StarCredits',
  'Starta',
  'Startcoin',
  'Status',
  'Stealthcoin',
  'Steem',
  'Steem Dollars',
  'Stellar Lumens',
  'Steps',
  'Sterlingcoin',
  'Storj',
  'Storjcoin X',
  'Stox',
  'Stratis',
  'Stress',
  'StrongHands',
  'Substratum',
  'Sumokoin',
  'SunContract',
  'SuperCoin',
  'SuperNET',
  'Suretly',
  'SwagBucks',
  'SwapToken',
  'Swapcoin',
  'Swarm City',
  'Swing',
  'Swisscoin',
  'SydPak',
  'Sync',
  'Syndicate',
  'Synereo',
  'Synergy',
  'Syscoin',
  'T-coin',
  'TAGRcoin',
  'TEKcoin',
  'TRON',
  'TaaS',
  'TagCoin',
  'TajCoin',
  'Tao',
  'Target Coin',
  'Tattoocoin (Limited Edition)',
  'Tattoocoin (Standard Edition)',
  'TeamUp',
  'TechShares',
  'Tellurion',
  'TenX',
  'TeraCoin',
  'TerraNova',
  'Terracoin',
  'TeslaCoilCoin',
  'TeslaCoin',
  'Tether',
  'Tezos (Pre-Launch)',
  'The ChampCoin',
  'The Cypherfunks',
  'The Vegan Initiative',
  'TheCreed',
  'TheGCCcoin',
  'Theresa May Coin',
  'Tickets',
  'Tierion',
  'Tigercoin',
  'TileCoin',
  'Titcoin',
  'TittieCoin',
  'ToaCoin',
  'TodayCoin',
  'TokenCard',
  'Tokes',
  'TopCoin',
  'Topaz Coin',
  'Torcoin',
  'Trackr',
  'Tracto',
  'Tradecoin',
  'TransferCoin',
  'TrezarCoin',
  'Triangles',
  'TrickyCoin',
  'Triggers',
  'Tristar Coin',
  'Trollcoin',
  'Truckcoin',
  'TrueFlip',
  'TrumpCoin',
  'TrustPlus',
  'TurboCoin',
  'Tychocoin',
  'Tyrocoin',
  'UFO Coin',
  'UG Token',
  'UGAIN',
  'UNCoin',
  'UR',
  'USDe',
  'Ubiq',
  'Ulatech',
  'Ultimate Secure Cash',
  'UltraCoin',
  'UnbreakableCoin',
  'UniCoin',
  'Unify',
  'Unitus',
  'Unity Ingot',
  'Universal Currency',
  'UniversalRoyalCoin',
  'Universe',
  'Unobtanium',
  'Unrealcoin',
  'Uro',
  'Useless Ethereum Token',
  'UtaCoin',
  'VIBE',
  'VIP Tokens',
  'VIVO',
  'VPNCoin',
  'Valorbit',
  'VapersCoin',
  'Vault Coin',
  'Vcash',
  'VeChain',
  'Vector',
  'VegasCoin',
  'Veltor',
  'Verge',
  'VeriCoin',
  'Veritaseum',
  'VeriumReserve',
  'Veros',
  'Version',
  'Vertcoin',
  'Viacoin',
  'Viberate',
  'Virta Unique Coin',
  'Virtacoin',
  'Virtacoinplus',
  'VirtualCoin',
  'Visio',
  'Voise',
  'Voxels',
  'Voyacoin',
  'Vsync',
  'WA Space',
  'WARP',
  'WMCoin',
  'Wagerr',
  'WalletBuildersCoin',
  'Walton',
  'Waves',
  'Waves Community Token',
  'WavesGo',
  'WayGuide',
  'WeAreSatoshi',
  'WeTrust',
  'Wexcoin',
  'WhaleCoin',
  'WhiteCoin',
  'Wi Coin',
  'Wild Beast Block',
  'Wild Crypto',
  'Wings',
  'Wink',
  'WomenCoin',
  'Woodcoin',
  'WorldCoin',
  'Wowcoin',
  'Wowecoin',
  'Wyvern',
  'X-Coin',
  'X2',
  'XCurrency',
  'XDE II',
  'XP',
  'XPlay',
  'XTD Coin',
  'XTRABYTES',
  'Xaucoin',
  'Xaurum',
  'Xonecoin',
  'YOYOW',
  'Yacoin',
  'YashCoin',
  'Yescoin',
  'Yocoin',
  'ZClassic',
  'ZCoin',
  'ZSEcoin',
  'Zayedcoin',
  'ZcCoin',
  'Zcash',
  'Zeitcoin',
  'ZenCash',
  'ZenGold',
  'Zennies',
  'Zero',
  'ZetaMicron',
  'Zetacoin',
  'Zeusshield',
  'Zilbercoin',
  'Zoin',
  'Zonecoin',
  'ZrCoin',
  'Zurcoin',
  'adToken',
  'bitBTC',
  'bitCNY',
  'bitEUR',
  'bitGold',
  'bitSilver',
  'bitUSD',
  'bitqy',
  'district0x',
  'e-Gulden',
  'eBTC',
  'eBoost',
  'eLTC',
  'eUSD',
  'iBank',
  'iCoin',
  'iDice',
  'iExec RLC',
  'iQuant',
  'iTicoin',
  'iXledger',
  'microCoin',
  'netBit',
  'vSlice',
  'vTorrent'
];

